In [1]:
from shared import *

wearable_equipped_df = get_wearable_types_df()

i = 1
for block in RARITY_FARMING_BLOCKS:
    wearable_equipped_df = wearable_equipped_df.join(get_wearable_equipped_df(block).rename(columns=lambda c: str(c) + '_rf' + str(i)), how='outer')
    i += 1

In [2]:
wearable_equipped_df.head()

,name,maxQuantity,rarityScoreModifier,NRG,AGG,SPK,BRN,NRG Effect,AGG Effect,SPK Effect,...,slotNames,rarity,equippedCount_rf1,ownerCount_rf1,equippedCount_rf2,ownerCount_rf2,equippedCount_rf3,ownerCount_rf3,equippedCount_rf4,ownerCount_rf4
id,,,,,,,,,,,,,,,,,,,,,
1,Camo Hat,1000,1,0,1,0,0,,+,,...,Head,common,59,52,215,87,240,93,262,133
2,Camo Pants,1000,1,0,1,0,0,,+,,...,Body,common,73,66,217,99,225,93,249,125
3,MK2 Grenade,1000,1,0,1,0,0,,+,,...,"Hand L, Hand R",common,91,78,314,155,336,137,361,189
4,Snow Camo Hat,500,2,0,1,1,0,,+,+,...,Head,uncommon,69,61,139,113,152,94,154,124
5,Snow Camo Pants,500,2,0,1,1,0,,+,+,...,Body,uncommon,81,69,136,105,131,81,146,112

In [3]:
wearable_equipped_df.describe()

,maxQuantity,rarityScoreModifier,NRG,AGG,SPK,BRN,equippedCount_rf1,ownerCount_rf1,equippedCount_rf2,ownerCount_rf2,equippedCount_rf3,ownerCount_rf3,equippedCount_rf4,ownerCount_rf4
count,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000
mean,337.200000,11.228571,0.028571,0.020408,0.053061,0.122449,68.881633,56.106122,141.142857,103.412245,165.865306,99.371429,179.159184,119.771429
std,331.646261,13.742837,1.542831,1.550909,1.280865,1.446203,87.735715,67.343907,125.127836,84.336644,131.121620,72.229745,144.009716,87.219461
min,5.000000,1.000000,-6.000000,-6.000000,-5.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,2.000000
25%,100.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44.000000,33.000000,56.000000,37.000000,67.000000,48.000000
50%,250.000000,5.000000,0.000000,0.000000,0.000000,0.000000,42.000000,36.000000,108.000000,90.000000,143.000000,87.000000,159.000000,113.000000
75%,500.000000,10.000000,1.000000,1.000000,0.000000,0.000000,103.000000,89.000000,208.000000,157.000000,232.000000,143.000000,255.000000,175.000000
max,1000.000000,50.000000,6.000000,6.000000,5.000000,6.000000,550.000000,398.000000,602.000000,416.000000,635.000000,373.000000,670.000000,415.000000

In [4]:
wearable_equipped_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245 entries, 1 to 315
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 245 non-null    object
 1   maxQuantity          245 non-null    int64
 2   rarityScoreModifier  245 non-null    int64
 3   NRG                  245 non-null    int64
 4   AGG                  245 non-null    int64
 5   SPK                  245 non-null    int64
 6   BRN                  245 non-null    int64
 7   NRG Effect           245 non-null    object
 8   AGG Effect           245 non-null    object
 9   SPK Effect           245 non-null    object
 10  BRN Effect           245 non-null    object
 11  slotNames            245 non-null    object
 12  rarity               245 non-null    object
 13  equippedCount_rf1    245 non-null    int64
 14  ownerCount_rf1       245 non-null    int64
 15  equippedCount_rf2    245 non-null    int64
 16  ownerCount_rf2       245 non-null    int64
 17  equippedCount_rf3    245 non-null    int64
 18  ownerCount_rf3       245 non-null    int64
 19  equippedCount_rf4    245 non-null    int64
 20  ownerCount_rf4       245 non-null    int64
dtypes: int64(14), object(7)
memory usage: 50.2+ KB

In [5]:
wearable_equipped_df.to_csv('db/wearable_equipped.csv')